// <auto-generated />
using System;
using MQReceiver;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MQReceiver.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20190311154740_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MQReceiver.PersonExt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Name");

                    b.Property<string>("Patronymic");

                    b.Property<bool>("Sex");

                    b.Property<string>("Surname");

                    b.Property<int>("Type");

                    b.Property<string>("Xmlstring");

                    b.HasKey("Id");

                    b.ToTable("PersonsDb");
                });
#pragma warning restore 612, 618
        }
    }
}
